import { CircleAlertIcon } from "lucide-react"

import { useCampusesPage } from "@/components/admin/campuses/campuses-context"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogPanel,
  DialogPopup,
  DialogTitle,
} from "@/components/ui/dialog"
import {
  Field,
  FieldDescription,
  FieldLabel,
} from "@/components/ui/field"
import { Form } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { modal } from "@/config"
import { classroomExampleNames } from "@/lib/campus-classroom-format"

export function EditCampusDialog() {
  const { state, actions } = useCampusesPage()

  return (
    <Dialog
      onOpenChange={(open) => {
        if (!open) actions.closeEdit()
      }}
      open={state.editing !== null}
    >
      <DialogPopup className={modal.dialogMd}>
        <DialogHeader>
          <DialogTitle>Edit campus</DialogTitle>
          <DialogDescription>The campus ID cannot be changed.</DialogDescription>
        </DialogHeader>
        <Form className="contents" onSubmit={actions.handleEditSave}>
          <DialogPanel className="flex flex-col gap-4">
            <Field>
              <FieldLabel htmlFor="edit-campus-id">Campus ID</FieldLabel>
              <Input
                disabled
                id="edit-campus-id"
                readOnly
                type="text"
                value={state.editing?.campus_id ?? ""}
              />
              <FieldDescription>Generated by the API.</FieldDescription>
            </Field>
            <Field>
              <FieldLabel htmlFor="edit-campus-name">Name</FieldLabel>
              <Input
                autoComplete="off"
                id="edit-campus-name"
                onChange={(event) =>
                  actions.changeEditName(event.currentTarget.value)
                }
                required
                type="text"
                value={state.editName}
              />
            </Field>
            <div className="flex flex-col gap-4 rounded-lg border border-dashed p-3">
              <p className="text-sm font-medium">Classroom name format</p>
              <FieldDescription>
                Optional. Leave blank for no classroom naming rule. When set, CDM
                can flag a room as a classroom only if its name matches this
                format.
              </FieldDescription>
              <Field>
                <FieldLabel htmlFor="edit-campus-prefixes">Allowed prefixes</FieldLabel>
                <Input
                  autoComplete="off"
                  id="edit-campus-prefixes"
                  onChange={(event) =>
                    actions.changeEditPrefixes(event.currentTarget.value)
                  }
                  placeholder="MPO, N, W, S, E, NW, SW, SE, NE"
                  type="text"
                  value={state.editPrefixesText}
                />
                <FieldDescription>
                  Comma-separated letters (1-10 each), up to 30 tokens.
                </FieldDescription>
              </Field>
              <Field>
                <FieldLabel htmlFor="edit-campus-digits">Digit count</FieldLabel>
                <Input
                  className="w-24"
                  id="edit-campus-digits"
                  inputMode="numeric"
                  onChange={(event) =>
                    actions.changeEditDigits(event.currentTarget.value)
                  }
                  placeholder="3"
                  type="text"
                  value={state.editDigitsText}
                />
              </Field>
              {classroomExampleNames(state.editPrefixesText, state.editDigitsText) ? (
                <FieldDescription>
                  Classroom names look like{" "}
                  <span className="font-mono">
                    {classroomExampleNames(state.editPrefixesText, state.editDigitsText)}
                  </span>
                </FieldDescription>
              ) : null}
            </div>
            {state.editError ? (
              <Alert variant="error">
                <CircleAlertIcon />
                <AlertTitle>Could not save</AlertTitle>
                <AlertDescription>{state.editError}</AlertDescription>
              </Alert>
            ) : null}
            {state.deleteError ? (
              <Alert variant="error">
                <CircleAlertIcon />
                <AlertTitle>Could not delete</AlertTitle>
                <AlertDescription>{state.deleteError}</AlertDescription>
              </Alert>
            ) : null}
          </DialogPanel>
          <DialogFooter>
            <Button
              onClick={actions.openDelete}
              type="button"
              variant="destructive-outline"
            >
              Delete
            </Button>
            <DialogClose render={<Button type="button" variant="ghost" />}>
              Cancel
            </DialogClose>
            <Button loading={state.updatePending} type="submit">
              Save changes
            </Button>
          </DialogFooter>
        </Form>
      </DialogPopup>
    </Dialog>
  )
}
